import type { Tour } from "./types";

export const tours: Tour[] = [
  {
    id: 1,
    title: "Paris City Tour",
    image: "images/img1.jpg",
    rating: 4.1,
    reviews: 650,
    price: 150,
    duration: "7 Days",
    pickup: true,
    favorite: true,
  },
  {
    id: 2,
    title: "Disneyland Paris",
    image: "images/img2.jpg",
    rating: 4.5,
    reviews: 650,
    price: 105,
    duration: "5 Days",
    pickup: true,
    favorite: true,
  },
  {
    id: 3,
    title: "River Cruise",
    image: "images/img3.jpg",
    rating: 4.0,
    reviews: 350,
    price: 100,
    duration: "6 Hours",
    pickup: true,
    favorite: true,
  },
  {
    id: 4,
    title: "Eiffel Tower",
    image: "images/img4.jpg",
    rating: 4.5,
    reviews: 650,
    price: 105,
    duration: "5 Days",
    pickup: true,
    favorite: true,
  },
  {
    id: 5,
    title: "Eiffel Tower",
    image: "images/img5.jpg",
    rating: 4.5,
    reviews: 650,
    price: 105,
    duration: "5 Days",
    pickup: true,
    favorite: true,
  },
  {
    id: 6,
    title: "Eiffel Tower",
    image: "images/img6.jpg",
    rating: 4.5,
    reviews: 650,
    price: 105,
    duration: "5 Days",
    pickup: true,
    favorite: true,
  },
  {
    id: 7,
    title: "Eiffel Tower",
    image: "images/img7.jpg",
    rating: 4.5,
    reviews: 650,
    price: 105,
    duration: "5 Days",
    pickup: true,
    favorite: true,
  },
  {
    id: 8,
    title: "Eiffel Tower",
    image: "images/img8.jpg",
    rating: 4.5,
    reviews: 650,
    price: 105,
    duration: "5 Days",
    pickup: true,
    favorite: true,
  },
];
